[package]
name = "serverNode"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "serverNode"
path = "src/main.rs"

[lib]
name = "serverNode"
path = "src/lib.rs"


[dependencies]
crossbeam = "0.8"
rand = "0.9.0-alpha.1"

[target.'cfg(loom)'.dependencies]
loom = "0.7"
